---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    CF_API_EMAIL: AgAf5zuBsDm7S84arzolTto9Ik7463MGJZkX8VsRyWO8l26gbPyrvd6RPCQANqIB+B+FuOcV/f3A52kmLphY1gc3tOQHv+cRWd1v8AeA7Vn+mfnjXN0wptl+gSQYfbG4bYletFHWbkeEVgrN5Ad+ICsQaP9SWmW/IW236zFrHYNn6yEztjITUqkg4J30zWRGEY/8jMKhNDMnPl0oL8TNucarOlg5U77INYpXvL2abttDu8xVCWMohmZrmb7YXPcW0Jl0vZ3n5jqBYf+9UmBzRWkb4c0kOpvSsDyZzXQzPvYZyIX1n1lQyHWPA7irlPxsLTpPbZaPwLpbOU4rhSIcoIUBZ+6SZ/yRUhn6J0UiMLLERtSSuZjlwHWetX5+X5RFXJ9dvXE3zpZLXbVGMAvY0AxIaOS1LXHD4qxxvi5HOYmf6NxChdrcl/kihMB3ZKC5o75Cb1/l6AbcDtrJs85DnZOD4hCHr4FxwOfrYK1lCAXOjP6pucQQfoLHpGsKTaFdo28Xd8tEPtFqQY1MUa0XF5tfINu+9D5OeSEc/YVwLzShUWBjs1tjz9bE65H5VsfPj9zcL9BK/so1O9fvE7DldzPVi5V/gcpQ7iYGmrnGFXIQAqUVCZTt0GsrW6xDCOVQtAdcfbwwuS5JXusZ7XznEJngWpuGgD1eIH5D6WcO1HRUhvklIonT7tMP18p/8Ogi6OVQ95HdU2Oh6XCBM7jNtmjbmA90OA==
    CF_DNS_API_TOKEN: AgBBnjQWtGNsPrD3Z37EpA2y24fsf58aZM63livB2+gXU0ZfYB+7YUHYi0O9IggstlLTl+bldrhPeg8DXYio/7ptsRLo52la8lOJ5qP5+3nSyIVjINv4kOel7ffYrbe7Z/pK8wquj7pNmaFkUWsb+FJtSjeZbjIyYdlhF2dAtRS/OjX1aN95E0dSt3X/+CG91DypSN40SoOLMqTPzUJrzeINYNN3I/LlrphcvVtm0rix4w6A+cLpwId7rz2OopaqliYWXLadXaiZZkn1OchUr4rvaHDvEpUAtXMwlMYMwGIgcqa7v6OWP8SV5htnn9oeiPNM+HZEFrPNsP/mIknNHPe29+G/7t4UokmvP41UxfbHyvyspMQzMjWsa37Ed1t7Uu4GTb9G4D4DGIn/f29JQNtc+G7dds672dCeBtn1fkz36nrvtYET3wDe1LZzkJ+KgXBgmMgnaWkNU1ggbQxyfzT2ru1hPTkEfQvoPFWwUFNuYLc72R/3nvn/gj9/exkpj9Xt6HpIxb1RvxFB8pICIMyAWJR+TYZgJdvUzqJt2Ebwg6ZbRBV2XhlqOYDiv8LhkdcBuCyZC5aNcVse1qVO82Ix5nkbyorWKj/rKmCZwHRv3pmZ78hQRqzPFrHZpxskqbTCgTxp3NcdHDt2+EX2FchdSALywchDJOtXR5lQqCyoJ5PW6Ic4E2uYyeS92tny7nyKJ9S1N8KshZk3YE24UDv+RUG6dSiTxxX4KACwUgZ2aPb3YV2ufabP
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: traefik
