apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reposilite

resources:
  - namespace.yaml
  - ingress-route.yaml

helmCharts:
  - name: reposilite
    repo: https://helm.reposilite.com/
    releaseName: reposilite
    namespace: reposilite
    valuesFile: values.yaml

patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: reposilite
    target:
      labelSelector: app.kubernetes.io/instance=reposilite